version: "3"
services:
  mc:
    container_name: J-mc
    image: itzg/minecraft-server
    ports:
      - 35565:25565
    environment:
      EULA: "TRUE"
      MEMORY: "6G"
      VERSION: "SNAPSHOT"

    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /opt/j-mc/data:/data
